// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5KuAzvGsKJMNRRD9pt-5fno2ilsFEX8',
    appId: '1:583385683146:web:aee692f072fea21c325033',
    messagingSenderId: '583385683146',
    projectId: 'pawtrust-fc777',
    authDomain: 'pawtrust-fc777.firebaseapp.com',
    storageBucket: 'pawtrust-fc777.firebasestorage.app',
    measurementId: 'G-3M07RMPRSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJoENbfUje8qWCsMa5XPiuXhsB4XUE058',
    appId: '1:583385683146:android:55af0ac23ba64856325033',
    messagingSenderId: '583385683146',
    projectId: 'pawtrust-fc777',
    storageBucket: 'pawtrust-fc777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXHSzL6jEVOipfVhPe98fIk0ARHVNYsnQ',
    appId: '1:583385683146:ios:1b66f920397315e5325033',
    messagingSenderId: '583385683146',
    projectId: 'pawtrust-fc777',
    storageBucket: 'pawtrust-fc777.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXHSzL6jEVOipfVhPe98fIk0ARHVNYsnQ',
    appId: '1:583385683146:ios:1b66f920397315e5325033',
    messagingSenderId: '583385683146',
    projectId: 'pawtrust-fc777',
    storageBucket: 'pawtrust-fc777.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP5KuAzvGsKJMNRRD9pt-5fno2ilsFEX8',
    appId: '1:583385683146:web:4d8b83067490f4dc325033',
    messagingSenderId: '583385683146',
    projectId: 'pawtrust-fc777',
    authDomain: 'pawtrust-fc777.firebaseapp.com',
    storageBucket: 'pawtrust-fc777.firebasestorage.app',
    measurementId: 'G-6GQV8JMRJ7',
  );
}
